spring:
  application:
    name: wms

  datasource:
    url: jdbc:postgresql://localhost:5432/wms
    username: wms
    password: wms
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

wms:
  security:
    admin:
      username: ${WMS_ADMIN_USERNAME}
      password: ${WMS_ADMIN_PASSWORD}
    employees:
      - username: jan.kowalski
        password: ${WMS_EMPLOYEE_PASSWORD}
      - username: anna.nowak
        password: ${WMS_EMPLOYEE_PASSWORD}
      - username: piotr.wisniewski
        password: ${WMS_EMPLOYEE_PASSWORD}
      - username: karolina.wojcik
        password: ${WMS_EMPLOYEE_PASSWORD}
      - username: michal.kaminski
        password: ${WMS_EMPLOYEE_PASSWORD}
      - username: zuzanna.lewandowska
        password: ${WMS_EMPLOYEE_PASSWORD}
      - username: natalia.szymanska
        password: ${WMS_EMPLOYEE_PASSWORD}


