spring:
  application:
    name: wms

  datasource:
    url: jdbc:postgresql://localhost:5432/wms
    username: wms
    password: wms
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

wms:
  security:
    admin:
      username: ${WMS_ADMIN_USERNAME}
      password: ${WMS_ADMIN_PASSWORD}
    employee:
      username: ${WMS_EMPLOYEE_USERNAME}
      password: ${WMS_EMPLOYEE_PASSWORD}


